export {
  PhCirclesFour,
  PhPhoneCall,
  PhPhone,
  PhBookOpenText,
  PhChatDots,
  PhList,
  PhCaretDown,
  PhInstagramLogo,
  PhYoutubeLogo,
  PhLinkedinLogo,
  PhMagnifyingGlass,
  PhX,
  PhWarningCircle,
  PhCheck,
  PhSortAscending,
  PhStar,
  PhCaretLeft,
  PhHouse,
  PhMagnifyingGlassPlus,
} from '@phosphor-icons/vue';
